### ISSUE TITLE
Reorganize plugins doc

### ISSUE THREAD

**Issue by pllim** [ejeschke/ginga#299]
In Ginga's documentation, under "The Ginga Viewer and Toolkit Manual", its Plugins page has _all_ the plugins on the same page, which is now too cluttered. It should be:
- [x] Further broken up into one sub-page per plugin. (#300)
- [x] Each plugin's sub-page should have the same consistent layout (see below; #548 ).
- [x] Have a way to automatically extract config examples and insert them into plugin docs? (~~For Item 4 below. Maybe see how Astropy `units` doc compiles the unit listing doc.~~ #305) 

Proposed layout:
1. Name of the plugin (usually its class name) as the page title.
2. A screenshot of the plugin in action, which should highlight the main features.
3. This is followed by a bunch of text that explains how to use the plugin, and any other information necessary (e.g., underlying assumptions of data, etc.).
4. An example config file that user can use to customize the plugin, if applicable.

Example proposed layout (in `stginga`) -- http://stginga.readthedocs.org/en/latest/plugins_manual/dqinspect.html

**Comment by pllim** [comment]
Done.
